//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seminario.Aplicativo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clase
    {
        public int secuenciador_id { get; set; }
        public System.Guid clase_id { get; set; }
        public string clase_numero { get; set; }
        public string clase_actividades_apertura { get; set; }
        public string clase_actividades_desarrollo { get; set; }
        public string clase_actividades_cierre { get; set; }
        public string clase_evidencias_aprendizaje { get; set; }
        public string clase_recursos { get; set; }
        public string clase_bibliografia { get; set; }
    
        public virtual Secuenciador Secuenciador { get; set; }
    }
}
