//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seminario.Aplicativo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Localidad
    {
        public int localidad_id { get; set; }
        public string localidad_nombre { get; set; }
        public string localidad_departamento { get; set; }
        public string localidad_tipo { get; set; }
    }
}
