//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seminario.Aplicativo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orientacion
    {
        public int orientacion_id { get; set; }
        public string orientacion_nombre { get; set; }
    }
}
