//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seminario.Aplicativo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Secuenciador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Secuenciador()
        {
            this.Clases = new HashSet<Clase>();
        }
    
        public int secuenciador_id { get; set; }
        public int usuario_id { get; set; }
        public bool secuenciador_publico { get; set; }
        public string secuenciador_datos_generales_nombre { get; set; }
        public string secuenciador_datos_generales_area { get; set; }
        public string secuenciador_datos_generales_asignatura { get; set; }
        public string secuenciador_datos_generales_curso { get; set; }
        public string secuenciador_datos_generales_institucion { get; set; }
        public string secuenciador_descripcion_tema_general { get; set; }
        public string secuenciador_descripcion_contenidos { get; set; }
        public string secuenciador_descripcion_numero_clases { get; set; }
        public string secuenciador_descripcion_autor { get; set; }
        public string secuenciador_descripcion_capacidades_a_desarrollar { get; set; }
        public string secuenciador_descripcion_propositos { get; set; }
        public string secuenciador_descripcion_objetivos { get; set; }
        public string secuenciador_descripcion_metodologia { get; set; }
        public string secuenciador_descripcion_orientaciones_generales_evaluacion { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clase> Clases { get; set; }
    }
}
