//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seminario.Aplicativo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ubicacion
    {
        public int ubicacion_Id { get; set; }
        public string ubicacion_nombre_lugar { get; set; }
        public string ubicacion_direccion { get; set; }
        public string ubicacion_latitud { get; set; }
        public string ubicacion_longitud { get; set; }
        public string ubicacion_telefono { get; set; }
        public string ubicacion_web { get; set; }
        public string ubicacion_mail { get; set; }
    }
}
